[kube_control_plane]
master01 ansible_host=10.220.147.67 ip=10.220.147.67 etcd_member_name=etcd1 ansible_user=master01 ansible_ssh_pass=master01 ansible_port=10022 ansible_become=yes ansible_become_pass=master01
master02 ansible_host=10.220.147.68 ip=10.220.147.68 etcd_member_name=etcd2 ansible_user=master02 ansible_ssh_pass=master02 ansible_port=10022 ansible_become=yes ansible_become_pass=master02
master03 ansible_host=10.220.147.69 ip=10.220.147.69 etcd_member_name=etcd3 ansible_user=master03 ansible_ssh_pass=master03 ansible_port=10022 ansible_become=yes ansible_become_pass=master03

[etcd]
master01 ansible_host=10.220.147.67 ip=10.220.147.67 etcd_member_name=etcd1 ansible_user=master01 ansible_ssh_pass=master01 ansible_port=10022 ansible_become=yes ansible_become_pass=master01
master02 ansible_host=10.220.147.68 ip=10.220.147.68 etcd_member_name=etcd2 ansible_user=master02 ansible_ssh_pass=master02 ansible_port=10022 ansible_become=yes ansible_become_pass=master02
master03 ansible_host=10.220.147.69 ip=10.220.147.69 etcd_member_name=etcd3 ansible_user=master03 ansible_ssh_pass=master03 ansible_port=10022 ansible_become=yes ansible_become_pass=master03

[kube_node]
worker01 ansible_host=10.220.147.70 ip=10.220.147.70 ansible_user=worker01 ansible_ssh_pass=worker01 ansible_port=10022 ansible_become=yes ansible_become_pass=worker01
worker02 ansible_host=10.220.147.64 ip=10.220.147.64 ansible_user=worker02 ansible_ssh_pass=worker02 ansible_port=10022 ansible_become=yes ansible_become_pass=worker02
worker03 ansible_host=10.220.147.65 ip=10.220.147.65 ansible_user=worker03 ansible_ssh_pass=worker03 ansible_port=10022 ansible_become=yes ansible_become_pass=worker03
worker04 ansible_host=10.220.147.66 ip=10.220.147.66 ansible_user=worker04 ansible_ssh_pass=worker04 ansible_port=10022 ansible_become=yes ansible_become_pass=worker04
