[kube_control_plane]
hyunsu-master1 ansible_host=192.168.1.122 ip=192.168.1.122 etcd_member_name=etcd1 ansible_user=hyunsu-master ansible_ssh_pass=qpwoeiru1768 ansible_become=yes ansible_become_pass=qpwoeiru1768

[etcd]
hyunsu-master1 ansible_host=192.168.1.122 ip=192.168.1.122 etcd_member_name=etcd1 ansible_user=hyunsu-master ansible_ssh_pass=qpwoeiru1768 ansible_become=yes ansible_become_pass=qpwoeiru1768

[kube_node]
hyunsu-worker1 ansible_host=192.168.1.121 ip=192.168.1.121 ansible_user=hyunsu-worker ansible_ssh_pass=qpwoeiru1768 ansible_become=yes ansible_become_pass=qpwoeiru1768
hyunsu-worker2 ansible_host=192.168.1.105 ip=192.168.1.105 ansible_user=hyunsu-worker ansible_ssh_pass=qpwoeiru1768 ansible_become=yes ansible_become_pass=qpwoeiru1768

[k8s_cluster:children]
kube_control_plane
kube_node
